#!/bin/bash

# dev-setup - Installs tools and packages for development purposes.
#
# Copyright (©) 2025 rathbunj15 <rathbunj15@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

declare -A OS_MAPPED_REQUIRED_PACKAGES

OS_MAPPED_REQUIRED_PACKAGES["Ubuntu"]="python3 python3-pip software-properties-common ansible"

OS_NAME=$(source /etc/os-release && echo "$NAME")

VERBOSE=false
install_aliases=true
install_scripts=true
install_packages=true
install_docker=false
install_oc=false
install_zsh=false
oc_url=""

function get_package_manager() {
    pkg_mgr=""

    os_name=$(source /etc/os-release && echo "$NAME")

    case "$os_name" in
        Ubuntu*|Debian*|"Linux Mint"*)
            pkg_mgr=$(readlink -f $(which apt-get))
            ;;

        SUSE*|*SUSE*|SLES*|"Red Hat Enterprise Linux"*)
            pkg_mgr=$(readlink -f $(which zypper))
            ;;

        Fedora*|CentOS*)
            # RHEL, Fedora, and CentOS use DNF or YUM
            if $(command -v dnf) &> /dev/null; then
                pkg_mgr=$(readlink -f $(which dnf))
            elif $(command -v yum) &> /dev/null; then
                echo "System does not have dnf installed, using yum instead."
                pkg_mgr=$(readlink -f $(which yum))
            fi
            ;;

        *)
            echo "Unsupported OS: $os_name"
            exit 1
            ;;
    esac

    if [[ $VERBOSE == true ]]; then
        echo "Using detected package manager $(basename $pkg_mgr)"
    fi
    
    echo $pkg_mgr
}

function install_required_repos() {
    case "$OS_NAME" in
        Ubuntu*|Debian*|"Linux Mint"*)
            repos=('ppa:ansible/ansible')
            for repo in "${repos[@]}"; do
                if [[ ! $(grep -rh "$pkg" /etc/apt/sources.list.d/) ]]; then
                    if [[ $VERBOSE == true ]]; then
                        echo "Installing package repository $repo..."
                    fi

                    add-apt-repository --yes --update $repo > /dev/null
                else
                    # Only print if the verbose flag is enabled
                    if [[ $VERBOSE == true ]]; then
                        echo "Repository $repo already installed. Skipping..."
                    fi
                fi
            done
            ;;
    esac
}

function install_required_packages() {
    IFS=' '

    # Read the correct array of packages and split them on the IFS (space)
    read -ra os_packages <<< "${OS_MAPPED_REQUIRED_PACKAGES[$OS_NAME]}"

    for pkg in "${os_packages[@]}"; do
        
        if [[ ! $(which "$pkg") ]]; then
            if [[ $VERBOSE == true ]]; then
                echo "Installing package $pkg..."
            fi

            # Install the package.
            $1 install -y $pkg > /dev/null

            if [[ $? != 0 ]]; then
                echo "Error: Failed to install $pkg..."
                exit 1
            fi

            if [[ $VERBOSE == true ]]; then
                echo "Successfully installed package $pkg."
            fi
        else
            if [[ $VERBOSE == true ]]; then
                echo "Package $pkg is already installed."
            fi
        fi
    done
}

function help() {
    local code=$1
    echo """
Usage: dev-setup [options]

Install tools, packages, scripts, aliases, and optionally docker or OpenShift CLI onto the local system.

By default, installs packages, scripts, and aliases. Use flags to install additional components.
Combined flags are supported, e.g., -dv for docker and verbose.

Options:
    -d, --docker       Install docker
    -oc, --openshift-cli <url>  Install the OpenShift CLI from the provided URL
    -v, --verbose      Enable verbose output
    -h, --help         Show this help
"""
    exit $1
}

function isDockerInstalled() {
    # Verify that docker is installed.
    if [[ ! $(which docker) ]]; then
        return false
    fi

    return true
}

function areAllScriptsInstalled() {
    # Check that all bin scripts are installed in /usr/local/bin.
    for file in bin/*; do
        if [[ ! -f "/usr/local/bin/$(basename $file)" ]]; then
            echo -e "\nScript $(basename $file) is not installed. Reinstalling all scripts..."
            return false
        fi
    done

    return true
}

function runPlaybook() {
    local playbookLocation="playbooks/$1"
    ansible-playbook $playbookLocation ${@:2}
}

function parse_args() {
    while [[ $# -gt 0 ]]; do
        if [[ $1 == --* ]]; then
            case $1 in
                --docker)
                    install_docker=true
                    shift
                    ;;
                --openshift-cli)
                    install_oc=true
                    oc_url=$2
                    shift 2
                    ;;
                --install-zsh|--zsh*)
                    install_zsh=true
                    shift
                    ;;
                --verbose)
                    VERBOSE=true
                    shift
                    ;;
                --help)
                    help 0
                    ;;
                *)
                    echo "Unknown option: $1"
                    help 1
                    ;;
            esac
        elif [[ $1 == -* ]]; then
            if [[ ${#1} -gt 2 ]]; then
                # combined short options
                for ((i=1; i<${#1}; i++)); do
                    char=${1:i:1}
                    case $char in
                        d)
                            install_docker=true
                            ;;
                        v)
                            VERBOSE=true
                            ;;
                        h)
                            help 0
                            ;;
                        z)
                            install_zsh=true
                            ;;
                        o)
                            echo "Cannot combine -o, use -oc or --openshift-cli"
                            help 1
                            ;;
                        *)
                            echo "Unknown option: -$char"
                            help 1
                            ;;
                    esac
                done
                shift
            else
                case $1 in
                    -d)
                        install_docker=true
                        shift
                        ;;
                    -oc)
                        install_oc=true
                        oc_url=$2
                        shift 2
                        ;;
                    -z)
                        install_zsh=true
                        shift
                        ;;
                    -v)
                        VERBOSE=true
                        shift
                        ;;
                    -h)
                        help 0
                        ;;
                    *)
                        echo "Unknown option: $1"
                        help 1
                        ;;
                esac
            fi
        else
            echo "Unknown argument: $1"
            help 1
        fi
    done
}

pkg_mgr_path=$(get_package_manager | tail -n 1)

install_required_repos
install_required_packages $pkg_mgr_path

parse_args "$@"

if [[ $install_aliases == true ]]; then
    runPlaybook install-aliases.yaml
fi

if [[ $install_scripts == true ]]; then
    runPlaybook install-scripts.yaml
fi

if [[ $install_packages == true ]]; then
    runPlaybook install-packages.yaml
fi

if [[ $install_docker == true ]]; then
    runPlaybook install-docker.yaml
fi

if [[ $install_oc == true ]]; then
    runPlaybook install-openshift-cli.yaml -e "oc_url=$oc_url"
fi

if [[ $install_zsh == true ]]; then
    runPlaybook install-zsh.yaml
fi