#!/bin/bash

# dev-setup - Installs tools and packages for development purposes.
#
# Copyright (©) 2025 rathbunj15 <rathbunj15@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

declare -A OS_MAPPED_REQUIRED_PACKAGES

OS_MAPPED_REQUIRED_PACKAGES["Ubuntu"]="python3 python3-pip software-properties-common ansible"

OS_NAME=$(source /etc/os-release && echo "$NAME")

# Colorized log helpers
COLOR_RESET='\033[0m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_RED='\033[0;31m'
COLOR_BLUE='\033[0;34m'

function log_info() {
    echo -e "${COLOR_GREEN}[INFO]${COLOR_RESET} $*"
}

function log_warning() {
    echo -e "${COLOR_YELLOW}[WARN]${COLOR_RESET} $*"
}

function log_error() {
    local exit_code=0
    if [[ "$1" =~ ^[0-9]+$ ]]; then
        exit_code=$1
        shift
    fi
    echo -e "${COLOR_RED}[ERROR]${COLOR_RESET} $*"
    if [[ $exit_code -ne 0 ]]; then
        exit $exit_code
    fi
}

function log_debug() {
    if [[ $VERBOSE == true ]]; then
        echo -e "${COLOR_BLUE}[DEBUG]${COLOR_RESET} $*"
    fi
}

VERBOSE=false
# install_aliases=false
# install_scripts=false
# install_packages=false
install_aliases=true
install_scripts=true
install_packages=true
install_docker=false
install_oc=false
install_zsh=false
config_vscode=false
config_windows_terminal=false
oc_url=""

function get_package_manager() {
    pkg_mgr=""

    os_name=$(source /etc/os-release && echo "$NAME")

    case "$os_name" in
        Ubuntu*|Debian*|"Linux Mint"*)
            pkg_mgr=$(readlink -f $(which apt-get))
            ;;

        SUSE*|*SUSE*|SLES*|"Red Hat Enterprise Linux"*)
            pkg_mgr=$(readlink -f $(which zypper))
            ;;

        Fedora*|CentOS*)
            # RHEL, Fedora, and CentOS use DNF or YUM
            if $(command -v dnf) &> /dev/null; then
                pkg_mgr=$(readlink -f $(which dnf))
            elif $(command -v yum) &> /dev/null; then
                echo "System does not have dnf installed, using yum instead."
                pkg_mgr=$(readlink -f $(which yum))
            fi
            ;;

        *)
            log_error 1 "Unsupported OS: $os_name"
            ;;
    esac

    if [[ $VERBOSE == true ]]; then
        log_debug "Using detected package manager $(basename $pkg_mgr)"
    fi
    
    echo $pkg_mgr
}

function install_required_repos() {
    case "$OS_NAME" in
        Ubuntu*|Debian*|"Linux Mint"*)
            repos=('ppa:ansible/ansible')
            for repo in "${repos[@]}"; do
                if [[ ! $(grep -rh "$pkg" /etc/apt/sources.list.d/) ]]; then
                    # Only print if the verbose flag is enabled
                    if [[ $VERBOSE == true ]]; then
                        log_debug "Installing package repository $repo..."
                    fi

                    add-apt-repository --yes --update $repo > /dev/null
                else
                    # Only print if the verbose flag is enabled
                    if [[ $VERBOSE == true ]]; then
                        log_debug "Repository $repo already installed. Skipping..."
                    fi
                fi
            done
            ;;
    esac
}

function install_required_packages() {
    IFS=' '

    # Read the correct array of packages and split them on the IFS (space)
    read -ra os_packages <<< "${OS_MAPPED_REQUIRED_PACKAGES[$OS_NAME]}"

    for pkg in "${os_packages[@]}"; do
        
        if [[ ! $(which "$pkg") ]]; then
            if [[ $VERBOSE == true ]]; then
                log_debug "Installing package $pkg..."
            fi

            # Install the package.
            $1 install -y $pkg > /dev/null

            if [[ $? != 0 ]]; then
                log_error 1 "Failed to install $pkg"
            fi

            if [[ $VERBOSE == true ]]; then
                log_info "Successfully installed package $pkg."
            fi
        else
            if [[ $VERBOSE == true ]]; then
                log_debug "Package $pkg is already installed."
            fi
        fi
    done
}

function help() {
    local code=$1
    echo """
Usage: dev-setup [options]

Install tools, packages, scripts, aliases, and optionally docker, OpenShift CLI, or VS Code configs onto the local system.

By default, installs packages, scripts, and aliases. Use flags to install additional components.
Combined flags are supported, e.g., -dv for docker and verbose.

Options:
    -d, --docker       Install docker
    -z, --install-zsh   Install zsh and set it as the default shell
    -c, --config-vscode  Configure VS Code terminal font and settings
    -oc, --openshift-cli <url>  Install the OpenShift CLI from the provided URL
    -v, --verbose      Enable verbose output
    -h, --help         Show this help

This script must be run as root. Use sudo or run as the root user.
"""
    exit $1
}

function check_if_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "This script must be run as root. Please run with sudo or as root user."
        exit 1
    fi
}

function are_aliases_up_to_date() {
    local aliases_file="$HOME/.bash_aliases"
    local source_file="misc/aliases"
    if [[ ! -f "$aliases_file" ]]; then
        return 1
    fi
    if ! grep -q "ANSIBLE MANAGED ALIASES" "$aliases_file"; then
        return 1
    fi
    local current_block=$(sed -n '/# BEGIN ANSIBLE MANAGED ALIASES/,/# END ANSIBLE MANAGED ALIASES/p' "$aliases_file" | sed '1d;$d')
    local source_content=$(cat "$source_file")
    if [[ "$current_block" != "$source_content" ]]; then
        return 1
    fi
    return 0
}

function are_scripts_up_to_date() {
    for file in bin/*; do
        local script_name=$(basename "$file")
        if [[ ! -f "/usr/local/bin/$script_name" ]]; then
            return 1
        fi
        if ! cmp -s "$file" "/usr/local/bin/$script_name"; then
            return 1
        fi
    done
    return 0
}

function are_packages_installed() {
    local packages=(ansible-lint zip unzip wget curl git make jq jid screen yq thefuck black pylint)
    for pkg in "${packages[@]}"; do
        if ! dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
            return 1
        fi
    done
    return 0
}

function run_playbook() {
    local playbookLocation="playbooks/$1"
    ansible-playbook $playbookLocation ${@:2}
}

function parse_args() {
    while [[ $# -gt 0 ]]; do
        if [[ $1 == --* ]]; then
            case $1 in
                --docker)
                    install_docker=true
                    shift
                    ;;
                --openshift-cli)
                    install_oc=true
                    oc_url=$2
                    shift 2
                    ;;
                --install-zsh|--zsh*)
                    install_zsh=true
                    shift
                    ;;
                --config-vscode)
                    config_vscode=true
                    shift
                    ;;
                --config-windows-terminal)
                    config_windows_terminal=true
                    shift
                    ;;
                --verbose)
                    VERBOSE=true
                    shift
                    ;;
                --help)
                    help 0
                    ;;
                *)
                    echo "Unknown option: $1"
                    help 1
                    ;;
            esac
        elif [[ $1 == -* ]]; then
            if [[ ${#1} -gt 2 ]]; then
                # combined short options
                for ((i=1; i<${#1}; i++)); do
                    char=${1:i:1}
                    case $char in
                        d)
                            install_docker=true
                            ;;
                        v)
                            VERBOSE=true
                            ;;
                        h)
                            help 0
                            ;;
                        z)
                            install_zsh=true
                            ;;
                        c)
                            config_vscode=true
                            ;;
                        w)
                            config_windows_terminal=true
                            ;;
                        *)
                            echo "Unknown option: -$char"
                            help 1
                            ;;
                    esac
                done
                shift
            else
                case $1 in
                    -d)
                        install_docker=true
                        shift
                        ;;
                    -c)
                        config_vscode=true
                        shift
                        ;;
                    -oc)
                        install_oc=true
                        oc_url=$2
                        shift 2
                        ;;
                    -z)
                        install_zsh=true
                        shift
                        ;;
                    -w)
                        config_windows_terminal=true
                        shift
                        ;;
                    -v)
                        VERBOSE=true
                        shift
                        ;;
                    -h)
                        help 0
                        ;;
                    *)
                        echo "Unknown option: $1"
                        help 1
                        ;;
                esac
            fi
        else
            echo "Unknown argument: $1"
            help 1
        fi
    done
}

parse_args "$@"

check_if_root

pkg_mgr_path=$(get_package_manager | tail -n 1)

install_required_repos
install_required_packages $pkg_mgr_path

if [[ $install_aliases == true ]] && ! are_aliases_up_to_date; then
    run_playbook install-aliases.yaml
fi

if [[ $install_scripts == true ]] && ! are_scripts_up_to_date; then
    run_playbook install-scripts.yaml
fi

if [[ $install_packages == true ]] && ! are_packages_installed; then
    run_playbook install-packages.yaml
fi

if [[ $install_docker == true ]]; then
    run_playbook install-docker.yaml
fi

if [[ $install_oc == true ]]; then
    run_playbook install-openshift-cli.yaml -e "oc_url=$oc_url"
fi

if [[ $install_zsh == true ]]; then
    run_playbook install-zsh.yaml
fi

if [[ $config_vscode == true ]]; then
    run_playbook config-vscode.yaml
fi

if [[ $config_windows_terminal == true ]]; then
    run_playbook config-windows-terminal.yaml
fi